name: test1
channels:
- astropy
- anaconda
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- atomicwrites=1.2.1=py35_0
- attrs=18.2.0=py35h28b3542_0
- blas=1.0=mkl
- intel-openmp=2019.0=118
- libcxx=4.0.1=hcfea43d_1
- libcxxabi=4.0.1=hcfea43d_1
- libgfortran=3.0.1=h93005f0_2
- more-itertools=4.3.0=py35_0
- pathlib2=2.3.2=py35_0
- pluggy=0.7.1=py35h28b3542_0
- psutil=5.4.7=py35h1de35cc_0
- py=1.6.0=py35_0
- pytest=3.8.1=py35_0
- pytest-openfiles=0.3.0=py35_0
- pytest-remotedata=0.3.0=py35_0
- six=1.11.0=py35_1
- pyephem=3.7.6.0=py35h470a237_0
- certifi=2016.2.28=py35_0
- cloog=0.18.0=0
- cycler=0.10.0=py35_0
- freetype=2.5.5=2
- gmp=6.1.0=0
- icu=54.1=0
- isl=0.12.2=1
- libpng=1.6.30=1
- matplotlib=1.5.3=np111py35_1
- mkl=2017.0.3=0
- mpc=1.0.3=0
- mpfr=3.1.5=0
- numpy=1.11.3=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=2
- readline=6.2=2
- setuptools=36.4.0=py35_1
- sip=4.18=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
prefix: /Users/davecoulter/anaconda/envs/test1

